name: SkinChanger
author: Teunboeke 
version: 1.0.0
main: Teunboeke\SkinChanger\main
api: 3.15.2
description: with this plugin you can change other players their skin


  
  
  
    
              
      
        
    
